# Generated by Django 5.2.4 on 2025-07-15 08:05

from django.db import migrations, models
import django.utils.timezone
import courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link'), ('text', 'Text Content')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.resource_file_path),
        ),
        migrations.AddField(
            model_name='resource',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
